### ISSUE TITLE
Add --no-tidy flag for object and field permissions

### ISSUE THREAD

**Issue by jimpdx** [ForceCLI/force-md#218]
The feature that automatically de-duplicates and orders the profile object and field permissions is great, but we need a flag to disable it from time to time. For example I want to add just one field into a profile, commit that change, open a PR, then go back and "tidy" the profiles and possibly open a separate PR. Having to pick the single change is very time consuming when there is a lot of "tidying to do" such as:

![image](https://github.com/ForceCLI/force-md/assets/867051/6755899c-17f6-43f9-91fd-528064e445dc)

**Comment by cwarden** [comment]
Closing this out for now.  I can't think of a good reason to want to keep metadata in a non-tidied format.  In this example, I would tidy first and commit, then add the new field perimssions.

`tidy --list` can be used in a pre-commit hook or CI process to ensure metadata is kept tidied.
